### ISSUE TITLE
Add experiences

### ISSUE THREAD

**Issue by Leo-am** [Leo-am/Leo-am.github.io#3]
**Describe the issue**

Add experiences, such as:
- 3-Minute Thesis, 
- Famelab, 
- OSA (Teach at the Beach)
- World Science Festival, 
- Pint of Science, 
- Interview to OSA.

**Task list**
- [ ] Gather links with all these experiences.
- [ ] Organise them into priority/chronological order
- [ ] Add pictures or videos.
- [ ] Write a small text to describe the experience.
- [ ] download OSA Interview
- [ ] check photos of Pint of Science/World Science Festival
- [ ] Optica Teach at the Beach
- [X] Added link to Famelab Presentation
